"""`landmarks:` and their source paint.

One of `pipeline.config`'s blocks (`P3-35f`, `Q133`) — moved whole, and imported
through `pipeline.config`, which re-exports every name here.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from pipeline.config_blocks.base import Material, _MaterialTable, _measures, _require


@dataclass(frozen=True)
class SourcePaint:
    """How a mesh-sourced hero is repainted from its source COLOR_0 (`P3-6`).

    Present on a `Landmark` it declares the model is not an authored `.glb`
    but the building's own source mesh, extracted and vertex-repainted by
    `pipeline/landmarks.py` and shipped as generated output — government-
    derived data that must never be committed (`LICENSING.md`).

    The four surfaces are **names into the city's `materials:` table**, not
    colours: every colour the city ships is declared in that table and nowhere
    else, which is what keeps `_check_reflectance` total.

    Ribbon strips are dark horizontal glazing bands at constant absolute
    elevations above the model base: `first_m + k * pitch_m` for `count`
    strips, each `thickness_m` tall. A strip the roofline has descended past
    simply has no wall surface left at its elevation — no clamping needed.

    The normal thresholds only *seed* the roof and soffit: a face is a roof
    seed where its unit normal's y exceeds `roof_normal_y`, a soffit seed
    below `-soffit_normal_y`. Each region then grows across every edge whose
    faces meet at less than `crease_deg` — a curved sweep is one surface, and
    it stays roof all the way down its roll rather than turning into banded
    wall the moment it passes the threshold (the defect the first repaint
    shipped). Growth stops at creases, which is where a roof actually ends
    and a wall begins. Everything with a centroid under `base_below_m` is
    base regardless of facing (piers, service base).

    `reference_texture` makes the paint consult the building's own aerial
    photo: the individualised (`…A0`) variant of the same mesh carries the
    photogrammetry texture, and a procedural ribbon is kept only where that
    photo is darker than the *same wall half a pitch above and below* — the
    one comparison that cancels the baked sun and shade, which vary across a
    facade at many times the glazing's own contrast. A band sample under
    `veto_ratio` x its vertical neighbours counts as glazing; a uniform
    surface (a roof sweep, a fascia) contrasts at ~1.0 and loses its bands.
    The texture never ships (`Q33`: the palette is the four named materials,
    nothing else); it only votes at build time, and it needs the city's
    `individualised` sheet zips on disk.
    """

    wall: Material
    ribbon: Material
    roof: Material
    base: Material
    ribbon_first_m: float
    ribbon_pitch_m: float
    ribbon_thickness_m: float
    ribbon_count: int
    base_below_m: float
    roof_normal_y: float = 0.5
    soffit_normal_y: float = 0.5
    crease_deg: float = 35.0
    reference_texture: bool = False
    veto_ratio: float = 0.9


@dataclass(frozen=True)
class Landmark:
    """One hero building: the model that replaces its source meshes
    (`P3-6`, contract in `docs/ARCHITECTURE.md` under `landmarks.json`).

    Two kinds, told apart by `source_paint`. Without it, the model is an
    authored `.glb` committed under `assets/authored/landmarks/` (CC BY-SA,
    generated by `tools/make_landmark.py`). With it, the model is the source
    mesh itself, extracted and repainted by `pipeline/landmarks.py` into
    generated output under `assets/generated/landmarks/` — which is why the
    asset root differs per kind and `rot_y_deg` must be zero for the second:
    the extracted mesh keeps its source orientation, and a bearing on top
    would rotate it twice.

    `replaces_source_ids` holds **stems** — the cross-dataset building key
    `docs/DATA_SOURCES.md` establishes and `buildings.stem` computes — not full
    source ids. The same keying `P3-7a`'s override table uses, and deliberately
    unvalidated in shape here (an id format is a publisher's spelling, hard
    rule 3); a stem that matches nothing is caught by `export.py`'s
    set-equality check against what the building stage actually dropped.
    **Optional for an authored asset since `P5-10`** — a prop standing beside
    the city replaces nothing, and this block is the door every hand-made
    `.glb` enters by (`Q121`). Required for a mesh-sourced hero, which is
    extracted *from* its stems.

    The position is authored in the city's projected CRS with elevation in the
    source datum, because that is what the surveyed blocks and meshes are
    published in — a number here can be checked against the sheet by eye.
    `export.py` converts it to game space; nothing downstream reads this form.

    `rot_y_deg` is a **compass bearing**: degrees clockwise from north, viewed
    from above — the convention `CityManifest.bearing_deg` already pins. The
    one conversion to a Godot rotation lives in the runtime's `landmarks.gd`.
    """

    id: str
    # `res://` path of the model — committed or generated per the kind above.
    asset: str
    easting: float
    northing: float
    elevation: float
    rot_y_deg: float
    # Display names, never rendered signage (`Q42`, hard rule 8).
    name_en: str
    name_zh: str
    replaces_source_ids: tuple[str, ...]
    # The in-engine ceiling `verify_landmarks.gd` holds each placed model to,
    # carried per entry in `landmarks.json`. The 8k default is ART_DESIGN.md's
    # authored-hero budget; a mesh-sourced hero pins its own measured ceiling.
    triangle_budget: int = 8000
    source_paint: SourcePaint | None = None


# Where a landmark's committed model must live. Game layout rather than city
# data — `docs/ARCHITECTURE.md` fixes it and CLAUDE.md commits the directory —
# so pinning it here is contract enforcement, not a hard-rule-3 violation.
# Public because `export.py`'s validator checks shipped documents against the
# same root: two spellings of the rule is how they come to disagree.
LANDMARK_ASSET_ROOT = "res://assets/authored/landmarks/"


# Where a mesh-sourced hero's repainted model lands instead. Generated output,
# gitignored, governed by the data publisher's terms rather than CC BY-SA —
# `LICENSING.md` is why the two roots must never be confused. Public for the
# same reason as `LANDMARK_ASSET_ROOT`.
LANDMARK_GENERATED_ROOT = "res://assets/generated/landmarks/"


# The surface roles a `source_paint` block must name, in the order the
# `SourcePaint` fields declare them.
_PAINT_SURFACES = ("wall", "ribbon", "roof", "base")


def _landmarks(entries: list[Any], where: str, table: _MaterialTable) -> tuple[Landmark, ...]:
    landmarks = tuple(
        _landmark(entry, f"{where}[{index}]", table) for index, entry in enumerate(entries)
    )
    seen: dict[str, str] = {}
    stems: dict[str, str] = {}
    for index, landmark in enumerate(landmarks):
        place = f"{where}[{index}]"
        if landmark.id in seen:
            raise ValueError(f"{place} reuses id {landmark.id!r}, declared at {seen[landmark.id]}")
        seen[landmark.id] = place
        for stem in landmark.replaces_source_ids:
            if stem in stems:
                # Two heroes claiming one building would have the second's
                # equality check fail on a stem the first already consumed —
                # a confusing report for a config-local mistake.
                raise ValueError(f"{place} replaces {stem!r}, already claimed at {stems[stem]}")
            stems[stem] = place
    return landmarks


def _landmark(body: dict[str, Any], where: str, table: _MaterialTable) -> Landmark:
    landmark_id = str(_require(body, "id", where))
    asset = str(_require(body, "asset", where))
    paint = (
        _source_paint(body["source_paint"], f"{where}:source_paint", table)
        if body.get("source_paint") is not None
        else None
    )
    rotation = _measures(body, where, ("rot_y_deg",))
    if paint is not None:
        # The stage derives the output path from the id, so the asset must be
        # exactly that derivation — a near-miss would ship a model the
        # manifest points past.
        expected = f"{LANDMARK_GENERATED_ROOT}{landmark_id}.glb"
        if asset != expected:
            raise ValueError(
                f"{where}:asset is {asset!r}, but a mesh-sourced landmark ships its "
                f"repainted source mesh as generated output — expected {expected!r}"
            )
        if rotation["rot_y_deg"] != 0.0:
            raise ValueError(
                f"{where}:rot_y_deg is {rotation['rot_y_deg']!r}, but a mesh-sourced "
                "landmark keeps its source orientation — a bearing on top would "
                "rotate it twice; author 0.0"
            )
    elif not asset.startswith(LANDMARK_ASSET_ROOT) or not asset.endswith(".glb"):
        raise ValueError(
            f"{where}:asset is {asset!r}, expected a .glb under {LANDMARK_ASSET_ROOT} — "
            "authored landmark models are committed there (docs/ARCHITECTURE.md)"
        )
    names = _require(body, "name", where)
    replaces = body.get("replaces_source_ids")
    if replaces is None:
        replaces = []
    if not isinstance(replaces, list):
        raise ValueError(f"{where}:replaces_source_ids must be a list of stems")
    if paint is not None and not replaces:
        # A mesh-sourced hero *is* its stems — the stage extracts the model from
        # them — so an empty list is a model with no source, not a free-standing
        # prop. An authored asset may stand beside the city replacing nothing
        # (`P5-10`); that is the door's ordinary case.
        raise ValueError(
            f"{where}:replaces_source_ids must name the stems a mesh-sourced landmark is "
            "extracted from"
        )
    position = _measures(
        _require(body, "pos", where), f"{where}:pos", ("easting", "northing", "elevation")
    )
    budget = body.get("triangle_budget", 8000)
    if not isinstance(budget, int) or isinstance(budget, bool) or budget <= 0:
        raise ValueError(f"{where}:triangle_budget is {budget!r}, expected a positive integer")
    return Landmark(
        id=landmark_id,
        asset=asset,
        easting=position["easting"],
        northing=position["northing"],
        elevation=position["elevation"],
        rot_y_deg=rotation["rot_y_deg"],
        name_en=str(_require(names, "en", f"{where}:name")),
        name_zh=str(_require(names, "zh", f"{where}:name")),
        replaces_source_ids=tuple(str(stem) for stem in replaces),
        triangle_budget=budget,
        source_paint=paint,
    )


def _source_paint(body: dict[str, Any], where: str, table: _MaterialTable) -> SourcePaint:
    surfaces = _require(body, "materials", where)
    ribbons = _require(body, "ribbons", where)
    strips = _measures(
        ribbons, f"{where}:ribbons", ("first_m", "pitch_m", "thickness_m"), positive=True
    )
    count = _require(ribbons, "count", f"{where}:ribbons")
    if not isinstance(count, int) or isinstance(count, bool) or count < 0:
        raise ValueError(f"{where}:ribbons:count is {count!r}, expected a non-negative integer")
    base = _measures(body, where, ("base_below_m",))
    if base["base_below_m"] < 0.0:
        raise ValueError(f"{where}:base_below_m is {base['base_below_m']!r}, expected >= 0")
    thresholds: dict[str, float] = {}
    for key in ("roof_normal_y", "soffit_normal_y", "veto_ratio"):
        if body.get(key) is None:
            continue
        value = _measures(body, where, (key,))[key]
        if not 0.0 < value <= 1.0:
            # 0 would claim every wall as roof (or veto every band); above 1
            # nothing ever matches and the knob silently does nothing.
            raise ValueError(f"{where}:{key} is {value!r}, expected within (0, 1]")
        thresholds[key] = value
    if body.get("crease_deg") is not None:
        crease = _measures(body, where, ("crease_deg",))["crease_deg"]
        if not 0.0 < crease < 180.0:
            # 0 never grows past the seed; 180 grows through every edge and
            # floods the whole mesh with the first seed's surface.
            raise ValueError(f"{where}:crease_deg is {crease!r}, expected within (0, 180)")
        thresholds["crease_deg"] = crease
    reference = body.get("reference_texture", False)
    if not isinstance(reference, bool):
        raise ValueError(f"{where}:reference_texture is {reference!r}, expected a boolean")
    wall, ribbon, roof, base_surface = (
        table.get(str(_require(surfaces, role, f"{where}:materials")), f"{where}:materials:{role}")
        for role in _PAINT_SURFACES
    )
    return SourcePaint(
        wall=wall,
        ribbon=ribbon,
        roof=roof,
        base=base_surface,
        ribbon_first_m=strips["first_m"],
        ribbon_pitch_m=strips["pitch_m"],
        ribbon_thickness_m=strips["thickness_m"],
        ribbon_count=count,
        base_below_m=base["base_below_m"],
        reference_texture=reference,
        **thresholds,
    )
